name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:21-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: "Deploy snapshot version"
        run: ./gradlew -Dorg.gradle.parallel=true publish --no-daemon --stacktrace -Dorg.gradle.internal.http.socketTimeout=90000 -Dorg.gradle.internal.http.connectionTimeout=90000
        env:
          ORG_GRADLE_PROJECT_paperUsername: ${{ secrets.ARTIFACTORY_USERNAME }}
          ORG_GRADLE_PROJECT_paperPassword: ${{ secrets.ARTIFACTORY_PASSWORD }}
